### ISSUE TITLE
How can i get number of possible requests for my billing plan

### ISSUE THREAD

**Issue by tst32** [justinpinkney/toonify-api-docs#4]
How to find out how many unused images are left using https://rapidapi.com ?

**Comment by justinpinkney** [comment]
I think there is an option in the menu for Subscription and Usage. Where you should be able to see the amount of usage. It's a bit hard for me to check though as obviously I don't have a paid subscription to my own API. If you're having issues seeing this I'd suggest contacting support@rapidapi.com

PS. if you want a one off update if you send me your rapidapi username I can check the current status for you (you can get in touch directly at help@toonify.photos.

![image](https://user-images.githubusercontent.com/605492/111871865-30106000-8984-11eb-81fb-e21d4c1007ed.png)

**Comment by tst32** [comment]
thanks!
