### ISSUE TITLE
Integration with PHP using Curl

### ISSUE THREAD

**Issue by ZineddineHarakat** [justinpinkney/toonify-api-docs#6]
Hello,

I tried integration toonify api with php using cUrl, below my code : 

$ch = curl_init();

$params = array('name'=>'@alex.jpg;type=image/jpeg');

curl_setopt($ch, CURLOPT_URL, 'https://toonify.p.rapidapi.com/v0/toonify');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$headers = array();
$headers[] = 'Accept: image/jpeg';
$headers[] = 'Content-Type: multipart/form-data';
$headers[] = 'X-Rapidapi-Host: toonify.p.rapidapi.com';
$headers[] = 'X-Rapidapi-Key: MY_KEY';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

print_r($result);

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

I get this error when i try to print the result :

 {"detail":[{"loc":["body","image"],"msg":"field required","type":"value_error.missing"}]}

Any idea please ?

**Comment by justinpinkney** [comment]
I think your line `$params = array('name'=>'@alex.jpg;type=image/jpeg');` should instead be: `$params = array('image'=>'@alex.jpg;type=image/jpeg');` 

Here's a full example generated by postman:

```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://toonify.p.rapidapi.com/v0/toonify',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('image'=> new CURLFILE('/my/photo.jpg')),
  CURLOPT_HTTPHEADER => array(
    'x-rapidapi-key: keyhere',
    'x-rapidapi-host: toonify.p.rapidapi.com'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

```

**Comment by ZineddineHarakat** [comment]
Sorry, but you havent used $params variable, should it be inside
HTTPHEADER instead of CURLFILE ?

Regards;

**Comment by justinpinkney** [comment]
Yeah sorry that wasn't very clear of me. The first line was my guess at how you need to edit your code snippet. The code block below was an unrelated snipped generated by postman. I have no idea about php so I'm just going off what postman is generating for me. In the api the image data in the form needs to have the name `image` in your original code it looks like it had the name `name`

**Comment by ZineddineHarakat** [comment]
Hello Justin,

Hope you are doing well, still struggling with getting things setup with
Curl and PHP :( .

Do you know if someone managed to do it before ?

Kind regards;
